-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.actividades (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  empresa_id uuid NOT NULL,
  tipo character varying NOT NULL,
  descripcion text NOT NULL,
  entidad_tipo character varying,
  entidad_id uuid,
  usuario_id uuid,
  fecha timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  metadata jsonb,
  CONSTRAINT actividades_pkey PRIMARY KEY (id),
  CONSTRAINT actividades_empresa_id_fkey FOREIGN KEY (empresa_id) REFERENCES public.empresas(id),
  CONSTRAINT actividades_usuario_id_fkey FOREIGN KEY (usuario_id) REFERENCES public.usuarios(id)
);
CREATE TABLE public.aprobaciones (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  empresa_id uuid NOT NULL,
  documento_tipo USER-DEFINED NOT NULL,
  documento_id uuid NOT NULL,
  regla_id uuid,
  usuario_solicita uuid,
  usuario_aprueba uuid,
  estado USER-DEFINED DEFAULT 'pendiente'::"EstadoAprobacion",
  comentario text,
  fecha_solicitud timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  fecha_respuesta timestamp without time zone,
  CONSTRAINT aprobaciones_pkey PRIMARY KEY (id),
  CONSTRAINT aprobaciones_empresa_id_fkey FOREIGN KEY (empresa_id) REFERENCES public.empresas(id),
  CONSTRAINT aprobaciones_regla_id_fkey FOREIGN KEY (regla_id) REFERENCES public.reglas_aprobacion(id),
  CONSTRAINT aprobaciones_usuario_solicita_fkey FOREIGN KEY (usuario_solicita) REFERENCES public.usuarios(id),
  CONSTRAINT aprobaciones_usuario_aprueba_fkey FOREIGN KEY (usuario_aprueba) REFERENCES public.usuarios(id)
);
CREATE TABLE public.audit_log (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  empresa_id uuid,
  usuario_id uuid,
  accion character varying NOT NULL,
  modulo character varying NOT NULL,
  entidad_tipo character varying,
  entidad_id uuid,
  datos_anteriores jsonb,
  datos_nuevos jsonb,
  ip_address character varying,
  user_agent text,
  fecha timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT audit_log_pkey PRIMARY KEY (id)
);
CREATE TABLE public.clientes (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  empresa_id uuid NOT NULL,
  codigo character varying,
  nombre character varying NOT NULL,
  nombre_comercial character varying,
  rnc_o_cedula character varying,
  tipo USER-DEFINED NOT NULL,
  direccion text,
  telefono character varying,
  correo character varying,
  contacto character varying,
  cargo_contacto character varying,
  tipo_pago USER-DEFINED DEFAULT 'contado'::"TipoPago",
  limite_credito numeric,
  dias_credito integer DEFAULT 0,
  descuento_general numeric DEFAULT 0,
  segmento character varying,
  industria character varying,
  etiquetas ARRAY,
  estado character varying DEFAULT 'activo'::character varying,
  notas text,
  fecha_creacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  fecha_actualizacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT clientes_pkey PRIMARY KEY (id),
  CONSTRAINT clientes_empresa_id_fkey FOREIGN KEY (empresa_id) REFERENCES public.empresas(id)
);
CREATE TABLE public.conduces (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  numero_conduce character varying NOT NULL,
  empresa_id uuid NOT NULL,
  sucursal_id uuid,
  cotizacion_id uuid,
  cliente_id uuid,
  equipo_id uuid,
  equipo_nombre character varying,
  placa character varying,
  tipo character varying,
  marca character varying,
  modelo character varying,
  año integer,
  conductor character varying,
  hora_salida time without time zone,
  hora_llegada time without time zone,
  hora_manana character varying,
  hora_tarde character varying,
  fecha date NOT NULL,
  lugar_origen character varying,
  lugar_destino character varying,
  grava_arena numeric,
  grava numeric,
  arena numeric,
  caliche numeric,
  bote_escombros numeric,
  otros text,
  subtotal numeric,
  monto_impuesto numeric,
  total numeric,
  entregado_por character varying,
  recibido_por character varying,
  firma_entrega text,
  firma_recibido text,
  estado character varying DEFAULT 'activo'::character varying,
  incluido_en_proforma boolean DEFAULT false,
  proforma_id uuid,
  url_pdf text,
  creado_por uuid,
  fecha_creacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT conduces_pkey PRIMARY KEY (id),
  CONSTRAINT conduces_empresa_id_fkey FOREIGN KEY (empresa_id) REFERENCES public.empresas(id),
  CONSTRAINT conduces_sucursal_id_fkey FOREIGN KEY (sucursal_id) REFERENCES public.sucursales(id),
  CONSTRAINT conduces_cotizacion_id_fkey FOREIGN KEY (cotizacion_id) REFERENCES public.cotizaciones(id),
  CONSTRAINT conduces_cliente_id_fkey FOREIGN KEY (cliente_id) REFERENCES public.clientes(id),
  CONSTRAINT conduces_equipo_id_fkey FOREIGN KEY (equipo_id) REFERENCES public.equipos(id)
);
CREATE TABLE public.cotizaciones (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  numero_cotizacion character varying NOT NULL,
  empresa_id uuid NOT NULL,
  sucursal_id uuid,
  cliente_id uuid NOT NULL,
  usuario_id uuid,
  moneda character varying DEFAULT 'DOP'::character varying,
  tasa_cambio numeric DEFAULT 1,
  titulo character varying,
  lugar character varying,
  fecha_emision date NOT NULL,
  valido_hasta date,
  estado USER-DEFINED DEFAULT 'borrador'::"EstadoDocumento",
  subtotal numeric DEFAULT 0,
  descuento_total numeric DEFAULT 0,
  monto_impuesto numeric DEFAULT 0,
  total numeric DEFAULT 0,
  total_moneda_base numeric DEFAULT round((total * tasa_cambio), 2),
  etapa character varying,
  probabilidad integer DEFAULT 0,
  fecha_cierre_estimada date,
  requiere_aprobacion boolean DEFAULT false,
  aprobado_por uuid,
  fecha_aprobacion timestamp without time zone,
  comentarios_aprobacion text,
  convertida_a_proforma boolean DEFAULT false,
  proforma_id uuid,
  convertida_a_factura boolean DEFAULT false,
  factura_id uuid,
  notas text,
  terminos_condiciones text,
  pago_al_contado boolean DEFAULT false,
  firma text,
  url_pdf text,
  creado_por uuid,
  fecha_creacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  fecha_actualizacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT cotizaciones_pkey PRIMARY KEY (id),
  CONSTRAINT cotizaciones_empresa_id_fkey FOREIGN KEY (empresa_id) REFERENCES public.empresas(id),
  CONSTRAINT cotizaciones_sucursal_id_fkey FOREIGN KEY (sucursal_id) REFERENCES public.sucursales(id),
  CONSTRAINT cotizaciones_cliente_id_fkey FOREIGN KEY (cliente_id) REFERENCES public.clientes(id),
  CONSTRAINT cotizaciones_usuario_id_fkey FOREIGN KEY (usuario_id) REFERENCES public.usuarios(id),
  CONSTRAINT cotizaciones_aprobado_por_fkey FOREIGN KEY (aprobado_por) REFERENCES public.usuarios(id)
);
CREATE TABLE public.cotizaciones_items (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  cotizacion_id uuid NOT NULL,
  producto_servicio_id uuid,
  descripcion text NOT NULL,
  cantidad numeric NOT NULL,
  unidad character varying,
  precio_unitario numeric NOT NULL,
  descuento numeric DEFAULT 0,
  tasa_impuesto numeric DEFAULT 0,
  monto_impuesto numeric DEFAULT 0,
  subtotal numeric NOT NULL,
  total numeric NOT NULL,
  notas text,
  orden integer DEFAULT 0,
  CONSTRAINT cotizaciones_items_pkey PRIMARY KEY (id),
  CONSTRAINT cotizaciones_items_cotizacion_id_fkey FOREIGN KEY (cotizacion_id) REFERENCES public.cotizaciones(id),
  CONSTRAINT cotizaciones_items_producto_servicio_id_fkey FOREIGN KEY (producto_servicio_id) REFERENCES public.productos_servicios(id)
);
CREATE TABLE public.empresas (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  nombre character varying NOT NULL,
  nombre_comercial character varying,
  rnc character varying NOT NULL UNIQUE,
  direccion text NOT NULL,
  telefono character varying NOT NULL,
  correo character varying NOT NULL,
  sitio_web character varying,
  logo text,
  moneda_base character varying DEFAULT 'DOP'::character varying,
  configuracion jsonb,
  estado character varying DEFAULT 'activo'::character varying,
  fecha_creacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  fecha_actualizacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT empresas_pkey PRIMARY KEY (id)
);
CREATE TABLE public.envios_documentos (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  empresa_id uuid NOT NULL,
  documento_tipo USER-DEFINED NOT NULL,
  documento_id uuid NOT NULL,
  destinatario character varying NOT NULL,
  metodo character varying NOT NULL,
  asunto character varying,
  mensaje text,
  adjuntos ARRAY,
  estado character varying DEFAULT 'pendiente'::character varying,
  error text,
  fecha_envio timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  fecha_entrega timestamp without time zone,
  enviado_por uuid,
  CONSTRAINT envios_documentos_pkey PRIMARY KEY (id),
  CONSTRAINT envios_documentos_empresa_id_fkey FOREIGN KEY (empresa_id) REFERENCES public.empresas(id),
  CONSTRAINT envios_documentos_enviado_por_fkey FOREIGN KEY (enviado_por) REFERENCES public.usuarios(id)
);
CREATE TABLE public.equipos (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  empresa_id uuid NOT NULL,
  codigo character varying,
  nombre character varying NOT NULL,
  placa character varying,
  tipo character varying,
  marca character varying,
  modelo character varying,
  año integer,
  estado character varying DEFAULT 'activo'::character varying,
  fecha_creacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT equipos_pkey PRIMARY KEY (id),
  CONSTRAINT equipos_empresa_id_fkey FOREIGN KEY (empresa_id) REFERENCES public.empresas(id)
);
CREATE TABLE public.facturas (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  numero_factura character varying NOT NULL,
  empresa_id uuid NOT NULL,
  sucursal_id uuid,
  proforma_id uuid,
  cotizacion_id uuid,
  cliente_id uuid NOT NULL,
  moneda character varying DEFAULT 'DOP'::character varying,
  tasa_cambio numeric DEFAULT 1,
  numero_ncf character varying UNIQUE,
  tipo_ncf USER-DEFINED,
  vigente_hasta date,
  fecha_emision date NOT NULL,
  fecha_vencimiento date,
  subtotal numeric DEFAULT 0,
  descuento_total numeric DEFAULT 0,
  valor_excento numeric DEFAULT 0,
  valor_gravado numeric DEFAULT 0,
  monto_impuesto numeric DEFAULT 0,
  itbis_18 numeric DEFAULT 0,
  total numeric DEFAULT 0,
  total_rd numeric DEFAULT 0,
  total_moneda_base numeric DEFAULT round((total * tasa_cambio), 2),
  estado_pago USER-DEFINED DEFAULT 'sin_pagar'::"EstadoPago",
  monto_pagado numeric DEFAULT 0,
  saldo_pendiente numeric DEFAULT 0,
  estado USER-DEFINED DEFAULT 'pendiente_pago'::"EstadoDocumento",
  enviado_dgii boolean DEFAULT false,
  fecha_envio_dgii timestamp without time zone,
  notas text,
  terminos_condiciones text,
  url_pdf text,
  creado_por uuid,
  fecha_creacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  fecha_actualizacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  anulado_por uuid,
  fecha_anulacion timestamp without time zone,
  razon_anulacion text,
  CONSTRAINT facturas_pkey PRIMARY KEY (id),
  CONSTRAINT facturas_empresa_id_fkey FOREIGN KEY (empresa_id) REFERENCES public.empresas(id),
  CONSTRAINT facturas_sucursal_id_fkey FOREIGN KEY (sucursal_id) REFERENCES public.sucursales(id),
  CONSTRAINT facturas_proforma_id_fkey FOREIGN KEY (proforma_id) REFERENCES public.proformas(id),
  CONSTRAINT facturas_cotizacion_id_fkey FOREIGN KEY (cotizacion_id) REFERENCES public.cotizaciones(id),
  CONSTRAINT facturas_cliente_id_fkey FOREIGN KEY (cliente_id) REFERENCES public.clientes(id)
);
CREATE TABLE public.facturas_items (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  factura_id uuid NOT NULL,
  producto_servicio_id uuid,
  descripcion text NOT NULL,
  cantidad numeric NOT NULL,
  unidad character varying,
  precio_unitario numeric NOT NULL,
  descuento numeric DEFAULT 0,
  tasa_impuesto numeric DEFAULT 0,
  monto_impuesto numeric DEFAULT 0,
  itbis numeric DEFAULT 0,
  subtotal numeric NOT NULL,
  total numeric NOT NULL,
  orden integer DEFAULT 0,
  CONSTRAINT facturas_items_pkey PRIMARY KEY (id),
  CONSTRAINT facturas_items_factura_id_fkey FOREIGN KEY (factura_id) REFERENCES public.facturas(id),
  CONSTRAINT facturas_items_producto_servicio_id_fkey FOREIGN KEY (producto_servicio_id) REFERENCES public.productos_servicios(id)
);
CREATE TABLE public.impuestos (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  empresa_id uuid NOT NULL,
  nombre character varying NOT NULL,
  tasa numeric NOT NULL,
  tipo character varying,
  descripcion text,
  activo boolean DEFAULT true,
  fecha_creacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT impuestos_pkey PRIMARY KEY (id),
  CONSTRAINT impuestos_empresa_id_fkey FOREIGN KEY (empresa_id) REFERENCES public.empresas(id)
);
CREATE TABLE public.numeraciones_documentos (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  empresa_id uuid NOT NULL,
  sucursal_id uuid,
  tipo_documento USER-DEFINED NOT NULL,
  prefijo character varying,
  siguiente_numero integer DEFAULT 1,
  formato character varying,
  activo boolean DEFAULT true,
  fecha_creacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT numeraciones_documentos_pkey PRIMARY KEY (id),
  CONSTRAINT numeraciones_documentos_empresa_id_fkey FOREIGN KEY (empresa_id) REFERENCES public.empresas(id),
  CONSTRAINT numeraciones_documentos_sucursal_id_fkey FOREIGN KEY (sucursal_id) REFERENCES public.sucursales(id)
);
CREATE TABLE public.pagos (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  factura_id uuid NOT NULL,
  empresa_id uuid NOT NULL,
  numero_pago character varying,
  fecha_pago date NOT NULL,
  monto numeric NOT NULL,
  moneda character varying DEFAULT 'DOP'::character varying,
  tasa_cambio numeric DEFAULT 1,
  monto_moneda_base numeric DEFAULT round((monto * tasa_cambio), 2),
  metodo USER-DEFINED NOT NULL,
  referencia character varying,
  banco character varying,
  cuenta character varying,
  comprobante_url text,
  notas text,
  estado character varying DEFAULT 'aplicado'::character varying,
  registrado_por uuid,
  fecha_creacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pagos_pkey PRIMARY KEY (id),
  CONSTRAINT pagos_factura_id_fkey FOREIGN KEY (factura_id) REFERENCES public.facturas(id),
  CONSTRAINT pagos_empresa_id_fkey FOREIGN KEY (empresa_id) REFERENCES public.empresas(id),
  CONSTRAINT pagos_registrado_por_fkey FOREIGN KEY (registrado_por) REFERENCES public.usuarios(id)
);
CREATE TABLE public.permisos (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  clave character varying NOT NULL UNIQUE,
  modulo character varying NOT NULL,
  accion character varying NOT NULL,
  descripcion text,
  activo boolean DEFAULT true,
  fecha_creacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT permisos_pkey PRIMARY KEY (id)
);
CREATE TABLE public.productos_servicios (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  empresa_id uuid NOT NULL,
  codigo character varying,
  nombre character varying NOT NULL,
  descripcion text,
  tipo USER-DEFINED NOT NULL,
  unidad character varying,
  precio_unitario numeric NOT NULL,
  costo numeric,
  tasa_impuesto numeric DEFAULT 18.00,
  categoria character varying,
  marca character varying,
  estado character varying DEFAULT 'activo'::character varying,
  fecha_creacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  fecha_actualizacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT productos_servicios_pkey PRIMARY KEY (id),
  CONSTRAINT productos_servicios_empresa_id_fkey FOREIGN KEY (empresa_id) REFERENCES public.empresas(id)
);
CREATE TABLE public.proformas (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  numero_proforma character varying NOT NULL,
  empresa_id uuid NOT NULL,
  sucursal_id uuid,
  cotizacion_id uuid,
  cliente_id uuid NOT NULL,
  moneda character varying DEFAULT 'DOP'::character varying,
  tasa_cambio numeric DEFAULT 1,
  fecha_emision date NOT NULL,
  fecha_inicio date,
  fecha_fin date,
  valido_hasta date,
  estado USER-DEFINED DEFAULT 'en_proceso'::"EstadoDocumento",
  subtotal numeric DEFAULT 0,
  descuento_total numeric DEFAULT 0,
  total_exc numeric DEFAULT 0,
  total_grav numeric DEFAULT 0,
  total_general numeric DEFAULT 0,
  monto_impuesto numeric DEFAULT 0,
  itbis_18 numeric DEFAULT 0,
  total numeric DEFAULT 0,
  total_rd numeric DEFAULT 0,
  total_moneda_base numeric DEFAULT round((total * tasa_cambio), 2),
  cotizacion_total numeric,
  variacion_monto numeric,
  variacion_porcentaje numeric,
  convertida_a_factura boolean DEFAULT false,
  factura_id uuid,
  observaciones text,
  cantidad_conduces integer DEFAULT 0,
  notas text,
  terminos_condiciones text,
  url_pdf text,
  creado_por uuid,
  fecha_creacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  fecha_actualizacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT proformas_pkey PRIMARY KEY (id),
  CONSTRAINT proformas_empresa_id_fkey FOREIGN KEY (empresa_id) REFERENCES public.empresas(id),
  CONSTRAINT proformas_sucursal_id_fkey FOREIGN KEY (sucursal_id) REFERENCES public.sucursales(id),
  CONSTRAINT proformas_cotizacion_id_fkey FOREIGN KEY (cotizacion_id) REFERENCES public.cotizaciones(id),
  CONSTRAINT proformas_cliente_id_fkey FOREIGN KEY (cliente_id) REFERENCES public.clientes(id)
);
CREATE TABLE public.proformas_items (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  proforma_id uuid NOT NULL,
  conduce_id uuid,
  producto_servicio_id uuid,
  numero_conduce character varying,
  fecha date,
  equipo character varying,
  descripcion text NOT NULL,
  cantidad numeric NOT NULL,
  unidad character varying,
  precio_unitario numeric NOT NULL,
  descuento numeric DEFAULT 0,
  tasa_impuesto numeric DEFAULT 0,
  monto_impuesto numeric DEFAULT 0,
  subtotal numeric NOT NULL,
  total numeric NOT NULL,
  orden integer DEFAULT 0,
  CONSTRAINT proformas_items_pkey PRIMARY KEY (id),
  CONSTRAINT proformas_items_proforma_id_fkey FOREIGN KEY (proforma_id) REFERENCES public.proformas(id),
  CONSTRAINT proformas_items_conduce_id_fkey FOREIGN KEY (conduce_id) REFERENCES public.conduces(id),
  CONSTRAINT proformas_items_producto_servicio_id_fkey FOREIGN KEY (producto_servicio_id) REFERENCES public.productos_servicios(id)
);
CREATE TABLE public.reglas_aprobacion (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  empresa_id uuid NOT NULL,
  nombre character varying NOT NULL,
  tipo_documento USER-DEFINED NOT NULL,
  condicion character varying NOT NULL,
  valor_minimo numeric,
  descuento_maximo numeric,
  rol_aprobador USER-DEFINED,
  usuario_aprobador_id uuid,
  activa boolean DEFAULT true,
  fecha_creacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT reglas_aprobacion_pkey PRIMARY KEY (id),
  CONSTRAINT reglas_aprobacion_empresa_id_fkey FOREIGN KEY (empresa_id) REFERENCES public.empresas(id),
  CONSTRAINT reglas_aprobacion_usuario_aprobador_id_fkey FOREIGN KEY (usuario_aprobador_id) REFERENCES public.usuarios(id)
);
CREATE TABLE public.roles_permisos (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  rol USER-DEFINED NOT NULL,
  permiso_id uuid NOT NULL,
  fecha_asignacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT roles_permisos_pkey PRIMARY KEY (id),
  CONSTRAINT roles_permisos_permiso_id_fkey FOREIGN KEY (permiso_id) REFERENCES public.permisos(id)
);
CREATE TABLE public.secuencias_ncf (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  empresa_id uuid NOT NULL,
  tipo USER-DEFINED NOT NULL,
  serie character varying NOT NULL,
  secuencia_actual integer DEFAULT 1,
  secuencia_inicial integer DEFAULT 1,
  secuencia_final integer NOT NULL,
  fecha_expiracion date NOT NULL,
  estado character varying DEFAULT 'activo'::character varying,
  fecha_creacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT secuencias_ncf_pkey PRIMARY KEY (id),
  CONSTRAINT secuencias_ncf_empresa_id_fkey FOREIGN KEY (empresa_id) REFERENCES public.empresas(id)
);
CREATE TABLE public.sesiones (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  usuario_id uuid NOT NULL,
  token character varying NOT NULL,
  refresh_token character varying,
  ip_address character varying,
  user_agent text,
  activa boolean DEFAULT true,
  expira_en timestamp without time zone NOT NULL,
  fecha_creacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  fecha_cierre timestamp without time zone,
  CONSTRAINT sesiones_pkey PRIMARY KEY (id),
  CONSTRAINT sesiones_usuario_id_fkey FOREIGN KEY (usuario_id) REFERENCES public.usuarios(id)
);
CREATE TABLE public.sucursales (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  empresa_id uuid NOT NULL,
  codigo character varying NOT NULL,
  nombre character varying NOT NULL,
  direccion text NOT NULL,
  telefono character varying,
  correo character varying,
  es_principal boolean DEFAULT false,
  estado character varying DEFAULT 'activo'::character varying,
  fecha_creacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT sucursales_pkey PRIMARY KEY (id),
  CONSTRAINT sucursales_empresa_id_fkey FOREIGN KEY (empresa_id) REFERENCES public.empresas(id)
);
CREATE TABLE public.usuarios (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  empresa_id uuid NOT NULL,
  sucursal_id uuid,
  auth_user_id uuid,
  nombre character varying NOT NULL,
  correo character varying NOT NULL UNIQUE,
  password_hash character varying,
  rol USER-DEFINED DEFAULT 'operador'::"RolUsuario",
  telefono character varying,
  avatar text,
  permisos_adicionales jsonb,
  configuracion jsonb,
  estado character varying DEFAULT 'activo'::character varying,
  intentos_fallidos integer DEFAULT 0,
  bloqueado_hasta timestamp without time zone,
  debe_cambiar_password boolean DEFAULT false,
  ultimo_acceso timestamp without time zone,
  ultima_ip character varying,
  fecha_creacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  fecha_actualizacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT usuarios_pkey PRIMARY KEY (id),
  CONSTRAINT usuarios_sucursal_id_fkey FOREIGN KEY (sucursal_id) REFERENCES public.sucursales(id),
  CONSTRAINT usuarios_empresa_id_fkey FOREIGN KEY (empresa_id) REFERENCES public.empresas(id)
);
CREATE TABLE public.usuarios_permisos (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  usuario_id uuid NOT NULL,
  permiso_id uuid NOT NULL,
  tipo character varying NOT NULL CHECK (tipo::text = ANY (ARRAY['permitir'::character varying, 'denegar'::character varying]::text[])),
  fecha_asignacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT usuarios_permisos_pkey PRIMARY KEY (id),
  CONSTRAINT usuarios_permisos_usuario_id_fkey FOREIGN KEY (usuario_id) REFERENCES public.usuarios(id),
  CONSTRAINT usuarios_permisos_permiso_id_fkey FOREIGN KEY (permiso_id) REFERENCES public.permisos(id)
);